PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Sales" (
	"ID"	INTEGER NOT NULL,
	"amount"	REAL NOT NULL DEFAULT 0.0,
	"salesDate"	TEXT NOT NULL,
	"region"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
INSERT INTO Sales VALUES(1,23456.0,'2021-12-22','w');
INSERT INTO Sales VALUES(2,12365.0,'2021-09-09','e');
INSERT INTO Sales VALUES(3,23757.0,'2020-11-11','e');
INSERT INTO Sales VALUES(4,12549.0,'2020-12-12','m');
INSERT INTO Sales VALUES(5,39393.0,'2021-02-02','w');
INSERT INTO Sales VALUES(7,15000.0,'2024-11-04','w');
CREATE TABLE IF NOT EXISTS "ImportedFiles" (
	"fileName"	TEXT NOT NULL,
	PRIMARY KEY("fileName")
);
INSERT INTO ImportedFiles VALUES('sales_q1_2021_w.csv');
CREATE TABLE IF NOT EXISTS "Region" (
	"code"	TEXT NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("code")
);
INSERT INTO Region VALUES('w','West');
INSERT INTO Region VALUES('m','Mountain');
INSERT INTO Region VALUES('c','Central');
INSERT INTO Region VALUES('e','East');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('Sales',7);
COMMIT;
